platform: x64

environment:
  nodejs_version: 8
  npm_config_target: 2.0.4
  npm_config_arch: x64
  npm_config_target_arch: x64
  npm_config_disturl: https://atom.io/download/electron
  npm_config_runtime: electron
  npm_config_build_from_source: true
  NODE_GYP_DIR: '%USERPROFILE%\.node-gyp'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
# install modules
  - npm i

build: off

only_commits:
  message: /chore\(package\) v\d+\.\d+\.\d+/

build_script:
    # Output useful info for debugging.
    - node --version
    - npm --version
    
    # run tests
    - npm run ci:dist

