environment:
  matrix:
  # node.js
  - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
   # install modules
  - npm i
  - npm i gritty

build: off

# Post-install test scripts.
build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm i electron-rebuild -g
  - npm run dist

