platform: x64

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
# Electron's version.
  - cmd: set npm_config_target=1.6.5
# The architecture of Electron, can be ia32 or x64.
  - cmd: set npm_config_arch=x64
  - cmd: set npm_config_target_arch=x64
# Download headers for Electron.
  - cmd: set npm_config_disturl=https://atom.io/download/electron
# Tell node-pre-gyp that we are building for Electron.
  - cmd: set npm_config_runtime=electron
   # Tell node-pre-gyp to build module from source code.
  - cmd: set npm_config_build_from_source=true
# install modules
  - npm i

build: off

only_commits:
  message: /chore\(package\) v\d+\.\d+\.\d+/

build_script:
    # Output useful info for debugging.
    - node --version
    - npm --version
    
    # run tests
    - npm run ci:dist

