platform: x64

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
   # install modules
  - npm i
  - npm i redrun -g
  - npm i electron-rebuild

build: off

# Post-install test scripts.
build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run ci:dist

