platform: x64

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
   # install modules
  - npm i

build: off

only_commits:
  message: /chore\(package\) v\d+\.\d+\.\d+/

build_script:
    # Output useful info for debugging.
    - node --version
    - npm --version
    
    # run tests
    - npm run ci:dist

