platform: x64

environment:
  nodejs_version: 12
  npm_config_target: 7.1.7
  npm_config_arch: x64
  npm_config_target_arch: x64
  npm_config_disturl: https://electronjs.org/headers
  npm_config_runtime: electron
  npm_config_build_from_source: true
  HOME: ~/.electron-gyp
  APPVEYOR_CACHE_SKIP_RESTORE: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
# install modules
  - npm i -f
  - npm i node-pty@beta

build: off

only_commits:
  message: /chore\(package\) v\d+\.\d+\.\d+/

build_script:
    # Output useful info for debugging.
    - node --version
    - npm --version
    
    # run tests
    - npm run ci:dist

