language: node_js
node_js:
    - 12

cache: false
sudo: required

script:
  - npm run lint

env:
    nodejs_version: 12
    npm_config_target: 6.0.5
    npm_config_arch: x64
    npm_config_target_arch: x64
    npm_config_disturl: https://electronjs.org/headers
    npm_config_runtime: electron
    npm_config_build_from_source: true

before_install:
  - sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* # hash mismatch fix
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install wine ; fi

# need this while node-pty@0.9.0 stable released
install:
  - npm i node-pty@beta
  - npm i

notifications:
    email:
        on_success: never
        on_failure: change

deploy:
    provider: script
    script: npm run ci:dist
    skip_cleanup: true
    on:
        node: '12'
        tags: true
        all_branches: false

