language: node_js
node_js:
    - 12

cache: false

script:
  - npm run lint

env:
    nodejs_version: 12
    npm_config_target: 6.0.2
    npm_config_arch: x64
    npm_config_target_arch: x64
    npm_config_disturl: https://atom.io/download/electron
    npm_config_runtime: electron
    npm_config_build_from_source: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install wine ; fi

notifications:
    email:
        on_success: never
        on_failure: change

deploy:
    provider: script
    script: npm run dist
    skip_cleanup: true
    on:
        node: '12'
        tags: true
        all_branches: false

